### ISSUE TITLE
sequences running over multiple lines are not handled correctly

### ISSUE THREAD

**Issue by kiramt** [QData/GaKCo-SVM#6]
It looks like fasta files where the sequences run over more than one line are being handled incorrectly e.g. fasta files which follow the convention of keeping lines below 80 characters.

I have data like this with 2686 entries where each sequence is the same length; each entry is in the format below:
>1
AGAGAAGAACAAGGCCATCACTAGAGCAGAGTGGTTGGAGATGAGCAAAGAAAAAATATTCCCGAAATACCATAGTCTCC
AAAAAAAAAACAATGCCCAAAAACCCAAAAACTCCAAAAAGGAAGGGCTTGGGCTGGGGCAGAGAG

i.e. 1 line for the description, 2 lines of sequence data

The entire file is 8058 lines long (so 3 x 2686)

The code calculates a kernel with 4029 lines instead of 2686, suggesting it is assuming that every second line is a sequence.

**Comment by rs3zz** [comment]
Yes, the way GaKCo is designed, it takes the input in the form 
>label
sequence
>label
sequence

and does not work on multi-line sequences. 
We will try and fix this issue. Thanks

**Comment by dblakely** [comment]
Hi Kira, to handle this problem for the time being, I wrote a python script you can use to convert your dataset into a format GaKCo (or iGakco) can read. It's located in src/scripts. I assumed that in the example you showed above, "1" is a class label (i.e., for positive sequences), not some other kind of sequence identifier. So the label lines should be -1, 0, or 1 (and nothing else, excepting whitespace). Sequences following the label lines can span any number of lines. To use it, you can simply run:
``
python gakco_formatter.py your_dataset.fasta dataset_gakco_format.fasta
``
And you'll be able to feed the ``dataset_gakco_format.fasta`` file into GaKCo or iGakco.

**Comment by kiramt** [comment]
I think this is missing the point a little.

Currently, if someone runs GaKCo with a multi-line fasta file (which is quite standard) it will run and produce results, but they will be completely wrong because it treats each sequence line as a separate data point. This is seriously bad behaviour. I would suggest that until a fix is ready you put something in your README to warn users and/or flag it when the code is run.

**Comment by rs3zz** [comment]
I think gakco_formatter.py script takes care of that issue, that is if you have a file like : 
1 
ATCG 
CCC
1 
AAA
TTT
it will be converted into 
1
ATCGCCC
1
AAATTT
Here, the multi-lines per label will be treated as one data point for that label. Thus they will not be treated as multiple data points. 
We will add this to the README and also elaborate on the input format GaKCo is expecting. 
If we are still missing something here, please let us know.

**Comment by kiramt** [comment]
That sounds ok - I think the important thing is that it's clear what format GaKCo is expecting so it doesn't silently do the wrong thing. The conversion step itself is fairly trivial, but you have to know it's required!

**Comment by dblakely** [comment]
Thanks, that's a great point. I updated the readme and GaKCo's help message to make it clearer what format we're expecting. I'm going to close this issue now. Handling a wider range of input formats is now on our todo list.
