### ISSUE TITLE
core dump with small example file

### ISSUE THREAD

**Issue by kiramt** [QData/GaKCo-SVM#7]
While running GaKCo with a small example file I get a core dump:

```
$ ./GaKCo -g 10 -k 4 temp.fasta dict.txt labels.txt kernel.txt
Input file : temp.fasta
Dictionary size = 5 (+1 for uknown character)
Reading temp.fasta
Read 2 strings of length = 12
Weights (hm):210 126 70 35 15 5 1 
numF=6, sumLen=24
(10,4): 6 features
*** Error in `./GaKCo': free(): invalid size: 0x00007fcbb4000c70 ***
*** Error in `./GaKCo': free(): invalid size: 0x00007fcbac000c70 ***
======= Backtrace: =========
```

temp.fasta:
```
>1
ACGACGTGACGA
>0
AGTCCCAAATCC
```

dict.txt:
```
A
C
G
T

```

**Comment by rs3zz** [comment]
I am assuming, you were able to figure this one out (based on Issue 3)

**Comment by kiramt** [comment]
Afraid not - I changed the parameters and it stopped core dumping, but it still core dumps with the case I used here

**Comment by dblakely** [comment]
I pushed a fix for this. The problem was occurring when the number of g-mers extracted from the dataset was less than g (a few arrays would overflow when this happened, causing the memory corruption you observed). Apologies for taking quite a while to fix this (been very busy the last 2 weeks).
